# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14_LyyrKK2sv2cGG3F1LFZD9614MGvvsy
"""

import numpy as np
import pandas as pd

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
names = ["sepal length", "sepal width", "petal length", "petal width", "class"]

df = pd.read_csv(url, names=names)

df.describe()

from sklearn import preprocessing

y = df.pop('class')

x=df

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(10,10),learning_rate="adaptive",activation="tanh",alpha=0.00001)

mlp.fit(x_train, y_train)

predictions = mlp.predict(x_test)

from sklearn.metrics import classification_report,confusion_matrix

print(confusion_matrix(y_test, predictions))

print(classification_report(y_test,predictions))



